[Desktop Entry]
Type=X-GNOME-Metatheme
Name=new_colors_new_life
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=new_colors_new_life
GtkTheme=oomox-new_colors_new_life
IconTheme=oomox-new_colors_new_life
MetacityTheme=oomox-new_colors_new_life
