#!/usr/bin/env zsh
set -x -e
ST_REPO=https://git.suckless.org/st
ST_SRC=$PWD/st
ST_CFG=$PWD/config.h
PATCHLIST=(
    st-bright-bold-text.patch
    st-clipboard.patch
    st-direct-terminfo.patch
    st-disable-intensity-styles.patch
    st-boxdraw_v2-0.8.2.diff
    st-alpha-0.8.2.diff
)
MAKE_OPTS=(
    PREFIX=$HOME/.local
)

if [[ ! -r $ST_SRC/.git/config ]]; then
    git clone $ST_REPO $ST_SRC
    cd $ST_SRC
else
    cd $ST_SRC
    git reset --hard
    git clean -fd
    git pull
fi

cp $ST_CFG .

for patch in $PATCHLIST; do
    patch --no-backup-if-mismatch -p1 -i ../$patch
done

make $MAKE_OPTS ${*:-install}
